# Generated by Django 2.2.5 on 2019-12-02 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comments',
            field=models.ManyToManyField(related_name='basketball_comments_owned', through='basketball.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
